---
- name: Configure HAProxy pour JFrog
  hosts: lb
  become: true
  vars:
    # backend_hosts sera lu depuis group_vars/all.yml
  tasks:
    - name: Ensure apt cache is up to date
      apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install haproxy
      apt:
        name: haproxy
        state: present

    - name: Deploy haproxy.cfg
      template:
        src: roles/haproxy/templates/haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
        owner: root
        group: root
        mode: '0644'
      notify: Restart haproxy

    - name: Ensure haproxy enabled and started
      service:
        name: haproxy
        state: started
        enabled: true

  handlers:
    - name: Restart haproxy
      service:
        name: haproxy
        state: restarted